public class CWS_AccountDataWrapper {
    public Account[] accountData;
    public Contact[] contactData;
    public Contract[] contractData;
    public Opportunity[] opportunityData;
    public OpportunityLineItem[] opportunityLineItemData;
    public SBQQ__Quote__c[] quoteData;
    public SBQQ__QuoteLine__c[] quoteLineData;
    public SBQQ__QuoteDocument__c[] quoteDocumentData;
    public SBQQ__Subscription__c[] subscriptionData;
    public Order[] orderData;
    public OrderItem[] orderItemData;
    public Zuora__Subscription__c[] zuoraSubscriptionData;
}